# 一、ndarray
## 1，ndarray的特性
### 多维性

In [1]:
import numpy as np

In [3]:
arr = np.array(5)  #创建0维的ndarray数组
print(arr)
print('arr的维度', arr.ndim) #数组的维度number of dimensions

5
arr的维度 0


In [7]:
arr = np.array([1, 2, 3])  #创建1维的ndarray数组
print(arr)
print('arr的维度', arr.ndim) #数组的维度number of dimensions

[1 2 3]
arr的维度 1


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  #创建2维的ndarray数组
print(arr)
print('arr的维度', arr.ndim) #数组的维度number of dimensions

[[1 2 3]
 [4 5 6]]
arr的维度 2


# 同质性

In [12]:
arr = np.array([1, 'hello'])  #不同的数据类型会被强制转换为相同的数据类型
print(arr)

['1' 'hello']


In [14]:
arr = np.array([1, 2.5])  #不同的数据类型会被强制转换为相同的数据类型
print(arr)

[1.  2.5]


## 2.ndarray的属性

In [18]:
arr = np.array(1)
print(arr)
print('数组的形状', arr.shape)
print('数组的形状', arr.ndim)
print('元素的个数', arr.size)
print('元素的数据类型', arr.dtype)
print('元素的转置', arr.T)

1
数组的形状 ()
数组的形状 0
元素的个数 1
元素的数据类型 int64
元素的转置 1


In [17]:
arr = np.array([1, 2.5, 3])
print(arr)
print('数组的形状', arr.shape)
print('数组的形状', arr.ndim)
print('元素的个数', arr.size)
print('元素的数据类型', arr.dtype)

[1.  2.5 3. ]
数组的形状 (3,)
数组的形状 1
元素的个数 3
元素的数据类型 float64


In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('数组的形状', arr.shape)
print('数组的形状', arr.ndim)
print('元素的个数', arr.size)
print('元素的数据类型', arr.dtype)
print('元素的转置\n', arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状 (2, 3)
数组的形状 2
元素的个数 6
元素的数据类型 int64
元素的转置
 [[1 4]
 [2 5]
 [3 6]]


## 3.ndarray的创建

In [24]:
# 基础的创建方法
list1 = [1, 2, 3]
arr = np.array(list1, dtype=np.float64)
print(arr.ndim) #属性
print(arr)

1
[1. 2. 3.]


In [29]:
# copy
arr1 = np.copy(arr) # 元素跟原始的数组相同，但不是一个数组
print(arr1)
arr1[0] = 5
print(arr1)
print(arr)

[1. 2. 3.]
[5. 2. 3.]
[1. 2. 3.]


In [33]:
# 预定义形状
# 全0 全1 未初始化 固定值
# 全0
arr = np.zeros((2,3), dtype=int)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [36]:
arr = np.zeros((2,), dtype=int)
print(arr)
print(arr.dtype)

[0 0]
int64


In [38]:
# 全1
arr = np.ones((5,8), dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [44]:
# 未初始化（数随机）
arr = np.empty((4,3))
print(arr)

[[9.42944498e-312 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 1.56055753e+161]
 [5.10620403e-066 9.57847039e+169 5.99293160e-066]
 [1.39358091e+165 7.40674892e-038 6.28293447e-038]]


In [46]:
arr = np.full((3,4), 2026)
print(arr)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [51]:
arr2 = np.ones_like(arr)
print(arr2)
arr3 = np.zeros_like(arr)
print(arr3)
arr4 = np.full_like(arr, 2026)
print(arr4)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [3]:
# 等差数列 1 2 3 4 5
arr = np.arange(1,10,1) #start/ end/ step
print(arr)

[1 2 3 4 5 6 7 8 9]


In [4]:
# 等差数列 1 2 3 4 5
arr = np.arange(2,11,2) #start/ end/ step
print(arr)

[ 2  4  6  8 10]


In [6]:
# 等间隔数列
app = np.linspace(1, 10, 5)
print(app)

[ 1.    3.25  5.5   7.75 10.  ]


In [10]:
# 等间隔数列
app = np.linspace(0, 100, 5, dtype=int)
print(app)
arr = np.arange(0, 101, 25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [14]:
# 对数间隔数列
arr = np.logspace(0, 4, 3, base=3, dtype=int)
print(arr)

[ 1  9 81]


In [16]:
# 特殊矩阵
# 单位矩阵
arr =np.eye(3, dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [17]:
# 对角矩阵
arr =np.diag([1, 2, 3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [19]:
# 随机数组的生成
# 生成0-1之间的随机浮点数（均匀分布）
arr = np.random.rand(2, 3)
print(arr)

[[0.07354291 0.06159466 0.34420692]
 [0.05596824 0.64971291 0.99184608]]


In [20]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3, 6, (2, 3))
print(arr)

[[4.78880853 5.91584566 5.57414051]
 [4.12137384 3.36291469 3.00196269]]


In [30]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3, 30, (2, 3))
print(arr)

[[10  8  5]
 [ 9 29 16]]


In [27]:
# 生成随机数列（正态分布）
arr = np.random.randn(2, 3)
print(arr)

[[ 0.32346101 -0.49341088 -0.79201679]
 [-0.84236793 -1.27950266  0.24571517]]


In [3]:
# 随机种子
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


### 4.ndarray的数据类型
### 布尔 bool
### 整数int 浮点数float 复数complex

In [12]:
arr = np.array([127, 0, 2, 0], dtype=np.int8)
print(arr)

[127   0   2   0]


### 5.索引与切片

In [17]:
# 一维数组的索引与切片
arr = np.random.randint(1, 100, 20)

In [18]:
print(arr)

[11 39 10 61 61 24 53 97 77 79 96 55 82 74 28 40 88 10 15 32]


In [31]:
print(arr[0])
print(arr[:]) #获取全部数据
print(arr[2:7]) #start:end+1(左包右不包)
print(arr[slice(2,15,2)]) #start.end,step
print(arr[(arr>10) & (arr<40)]) #布尔索引

11
[11 39 10 61 61 24 53 97 77 79 96 55 82 74 28 40 88 10 15 32]
[10 61 61 24 53]
[10 61 53 77 96 82 28]
[11 39 24 28 15 32]


In [32]:
# 二维数组的索引与切片
arr = np.random.randint(1, 100, (4,8))
print(arr)

[[57 57 59 80 28 51 75 70]
 [ 3 58 24 96 26 42 10 67]
 [16 66 31 89 50 41 12 70]
 [ 1 59 87 38 69 19 10 58]]


In [48]:
print(arr[1,1]) #索引
print(arr[0:3,1])
print(arr[2][arr[2]>50])
print(arr[:,3])

58
[57 58 66]
[66 89 70]
[80 96 89 38]


### 6.ndarray的运算

In [8]:
# 算术的运算
a = np.array([1, 2, 3])
b = np.array([2, 2, 3])
print(a + b)

[3 4 6]


In [11]:
c = [1, 3, 3]
d = [2, 3, 4]
for i in range(len(c)):
    d[i] = d[i] + c[i]
print(d)

[3, 6, 7]


In [15]:
# 二维计算
a = np.array([[1, 4, 5],[6, 5, 8],[1, 2, 3]])
b = np.array([[2, 2, 3],[4, 7, 9],[9, 5, 4]])
print(a * b)

[[ 2  8 15]
 [24 35 72]
 [ 9 10 12]]


In [13]:
# 数组与标量计算
a = np.array([[1, 4, 5],[6, 5, 8],[1, 2, 3]])
print(a + 3)

[[ 4  7  8]
 [ 9  8 11]
 [ 4  5  6]]


In [17]:
# 广播机制:1.获取形状2/是否可广播
a = np.array([1, 2, 3]) #1*3
b = np.array([[2], [2], [3]]) #3*1
print(a * b)

[[2 4 6]
 [2 4 6]
 [3 6 9]]


In [18]:
# 矩阵运算
a = np.array([[1, 4, 5],[6, 5, 8],[1, 2, 3]])
b = np.array([[2, 2, 3],[4, 7, 9],[9, 5, 4]])
print(a @ b)

[[ 63  55  59]
 [104  87  95]
 [ 37  31  33]]


# numpy中的常用函数
## 1.基本数学函数

In [5]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1, 4, 9]))
arr = np.array([1, 25, 81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [7]:
# 计算指数
print(np.exp(1))

2.718281828459045


In [10]:
# 计算自然对数
print(np.log(3))

1.0986122886681098


In [11]:
# 计算正余弦
print(np.sin(np.pi/2))

1.0


In [12]:
# 计算绝对值
arr = np.array([-1, 1, 2, -1])
print(np.abs(arr))

[1 1 2 1]


In [13]:
# 计算a的b次幂
print(np.power(arr, 2))

[1 1 4 1]


In [16]:
# 四舍五入
print(np.round([3.2, 4.6, 5]))

[3. 5. 5.]


In [18]:
# 向上取整，向下取整
arr = np.array([1.5, 2.4, 6.9])
print(np.ceil(arr))# 向上取整
print(np.floor(arr))# 向下取整

[2. 3. 7.]
[1. 2. 6.]


In [20]:
# 检测却始终NaN
np.isnan([1, 3, np.nan, 4])

array([False, False,  True, False])

# 2。统计函数
## 求和，平均值，中位数，标准差，方差， 查找最大值、最小值，分位数，累计和，累计差

In [4]:
arr = np.random.randint(1, 20, 8)
print(arr)

[16 16  4  5 12 10  6  2]


In [5]:
# 求和
print(np.sum(arr))

71


In [10]:
# 求平均值
print(np.average(arr))
print(np.mean(arr))

8.875
8.875


In [13]:
# 计算中位数
print(np.median(arr))
print(np.median([1, 2, 3, 4]))

8.0
2.5


In [14]:
# 计算标准差和方差
print(np.var([1, 2, 3]))#方差
print(np.std([1, 2, 3]))#标准差

0.6666666666666666
0.816496580927726


In [19]:
# 计算最大值和最小值
print(arr)
print(np.max(arr), np.argmax(arr))
print(np.min(arr), np.argmin(arr))

[16 16  4  5 12 10  6  2]
16 0
2 7


In [27]:
# 分位数
np.random.seed(0)
arr = np.random.randint(0, 100, 4)
print(arr)
print(np.median(arr))
print(np.percentile(arr, 20))

[44 47 64 67]
55.5
45.8


In [2]:
# 累积的和，累积的积
arr = np.array([1, 2, 3])
print(np.cumsum(arr))
print(np.cumprod(arr))

[1 3 6]
[1 2 6]


# 比较函数
### 比较是否大于、小于、等于
### 逻辑与、或、非
### 检查数组中是否有一个True,是否所有都为True,自定义条件

In [6]:
# 是否大于
print(np.greater([3, 4, 5, 6, 7], 4))
# 是否小于
print(np.less([3, 4, 5, 6, 7], 4))
# 是否等于
print(np.equal([3, 4, 5, 6, 7], 4))
print(np.equal([3, 4, 5], [6, 7, 8]))# 同形状

[False False  True  True  True]
[ True False False False False]
[False  True False False False]
[False False False]


In [12]:
print(np.logical_and([0, 0], [1, 1]))
print(np.logical_or([0, 0], [1, 1]))
print(np.logical_not([1, 0]))

[False False]
[ True  True]
[False  True]


In [14]:
# 检查元素是否至少有一个元素为True
print(np.any([1, 0]))
# 检查元素是否全部为True
print(np.all([1, 0]))

True
False


In [16]:
# 自定义条件
# print(np.where(条件,符合条件,不符合条件))
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr>3, arr, 0))

[0 0 0 4 5]


In [18]:
score = np.random.randint(50, 100, 20)
print(score)
print(np.where(score>=60, '及格', '不及格'))

[77 74 72 65 76 69 65 86 87 74 81 99 84 80 64 56 81 86 51 60]
['及格' '及格' '及格' '及格' '及格' '及格' '及格' '及格' '及格' '及格' '及格' '及格' '及格' '及格'
 '及格' '不及格' '及格' '及格' '不及格' '及格']


In [19]:
print(np.where(
    score<60,'不及格',np.where(
        score<80, '良好', '优秀'
    )
))

['良好' '良好' '良好' '良好' '良好' '良好' '良好' '优秀' '优秀' '良好' '优秀' '优秀' '优秀' '优秀'
 '良好' '不及格' '优秀' '优秀' '不及格' '良好']


In [22]:
# np.select(条件， 返回的结果）
print(np.select([score>80,(score>60)&(score<=80),score<60],
                ['优秀','良好','不及格'],
                default='No'))

['良好' '良好' '良好' '良好' '良好' '良好' '良好' '优秀' '优秀' '良好' '优秀' '优秀' '优秀' '良好'
 '良好' '不及格' '优秀' '优秀' '不及格' 'No']


In [7]:
# 排序函数
np.random.seed(0)
arr = np.random.randint(1, 100, 20)
print(arr)
print(np.sort(arr))
print(np.argsort(arr))
print(arr)#不被污染

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6  9 17 11 12 19]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]


In [8]:
# 去重函数
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [14]:
# 数组的拼接
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1,arr2)))

[1 2 3 4 5 6]


In [17]:
# 数组的切割
print(np.split(arr,5))
print(np.split(arr,[6,12,18]))

[array([45, 48, 65, 68], dtype=int32), array([68, 10, 84, 22], dtype=int32), array([37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66], dtype=int32), array([40, 88, 47, 89], dtype=int32)]
[array([45, 48, 65, 68, 68, 10], dtype=int32), array([84, 22, 37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66, 40, 88], dtype=int32), array([47, 89], dtype=int32)]


In [18]:
# 调整数组的形状
print(np.reshape(arr,[4,5]))

[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]


In [24]:
arr = np.array([28,30,29,31,32,30,29])
print(np.average(arr))
print(np.max(arr))
print(np.min(arr))
print(len(arr[arr>30]))

29.857142857142858
32
28
2


In [25]:
score = np.array([85,90,78,92,88])
print(np.average(score))
print(np.median(score))
print(np.std(score))

86.6
88.0
4.882622246293481


In [33]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
print(A + B)
print(A * B)
print(A@B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [37]:
np.random.seed(0)
np.arr = np.random.randint(0,11,(3,4))
print(arr)
print(np.max(arr,axis=0))#axis=0为列  axis=1为行

[[3 8 1 3]
 [3 3 7 0]
 [1 9 9 0]]
[3 9 9 3]


In [7]:
arr = np.arange(1,13)
print(arr)
arr = np.reshape(arr,(3,4))
print(arr)
print('每行的和', np.sum(arr,axis=1))# 等于1是行
print('每列的平均值', np.mean(arr,axis=0))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和 [10 26 42]
每列的平均值 [5. 6. 7. 8.]


In [11]:
np.random.seed(0)
arr = np.random.randint(0,20,(5,5))
print(arr)
print(arr[arr>10])
arr[arr>10] = 0
print(arr)

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [12]:
arr = np.array([2,1,2,3,1,4,3])
u_arr, counts = np.unique(arr, return_counts=True)
print(u_arr)
print(counts)

[1 2 3 4]
[2 2 2 1]
